import { Inter } from "next/font/google";
import "./globals.css";
import clsx from 'clsx'
import { Variable } from "lucide-react";

const inter = Inter({ subsets: ["latin"],
  variable: "--font-inter" });

 

// This is the root layout for a Next.js application.


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, "bg-background text-foreground")}>{children}</body>
    </html>
  );
}
